server-website/Nostradabus.Website/Controllers/CheckpointController.cs
using System;
using System.Collections.Generic;
using System.Device.Location;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Nostradabus.BusinessComponents;
using Nostradabus.BusinessComponents.Exceptions;
using Nostradabus.BusinessEntities;
using Nostradabus.Website.Models;

namespace Nostradabus.Website.Controllers
{
    public class CheckpointController : Controller
	{
		#region Add

		public ActionResult Add()
        {
        	var model = new CheckpointModel();

			return View(model);
        }

		[HttpPost]
		public ActionResult Add(CheckpointModel model)
		{
			try
			{
				var checkpoint = ToEntity(model);

				CheckpointComponent.Instance.Add(checkpoint);

				model.Messages.Add("Se ha registrado el checkpoint con éxito");
			}
			catch (ValidationException ex)
			{
				model.AddValidationErrors(ex);
			}
			catch (Exception ex)
			{
				model.ErrorMessages.Add(Resources.Global.ErrorMessage);

				Common.Logger.LoggingManager.Logging.Error(ex);
			}
			return View(model);
		}

		#endregion Add

		#region DataEntry

		public ActionResult DataEntry()
		{
			var model = new DataEntryModel();

			return View(model);
		}
		
		#endregion Add

		#region Private Methods

		private static Checkpoint ToEntity(CheckpointModel model)
		{
			var entity = new Checkpoint
			{
			    Route = RouteComponent.Instance.GetById(model.RouteId), 
				UUID = model.UUID,
				DateTime = model.DateTime
			};
			
			if(model.Latitude.HasValue && model.Longitude.HasValue)
			{
				entity.Coordinate = new GeoCoordinate(model.Latitude.Value, model.Longitude.Value);
			}
			
			return entity;
		}

    	#endregion Provate Methods

	}
}

server-website/Nostradabus.Website/Controllers/MobileController.cs
using System;
using System.Collections.Generic;
using System.Device.Location;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Nostradabus.BusinessComponents;
using Nostradabus.BusinessComponents.Exceptions;
using Nostradabus.BusinessEntities;
using Nostradabus.BusinessEntities.Common;
using Nostradabus.Common;
using Nostradabus.WebSite.CustomActionResults;
using Nostradabus.WebSite.Models;
using Nostradabus.Website.Models;

namespace Nostradabus.Website.Controllers
{
    public class MobileController : Controller
    {
		[HttpGet]
		public ActionResult GetNearbyLines(double? latitude, double? longitude)
        {
			try
			{
				#region Validations

				if (!latitude.HasValue) throw new ValidationException("El parámetro 'latitude' es requerido.");

				if (!longitude.HasValue) throw new ValidationException("El parámetro 'longitude' es requerido");

				#endregion Validations

				var model = new NearbyLinesModel {
		           Lines = RouteComponent.Instance.GetNearbyLines(new GeoCoordinate(latitude.Value, longitude.Value)).ToArray()
            	};
				
				#region Mock

				/*
				var rnd = new Random();
				var responseSelector = rnd.Next(1, 7); // creates a number between 1 and 6
				switch(responseSelector)
				{
					case 1:
						model.Lines = new[] { 5, 7, 19, 32, 41, 51, 61, 64, 68, 71, 75, 86, 88, 98, 101, 104, 105, 115, 118, 129, 132, 151, 165, 168, 188 };
						break;

					case 2:
						model.Lines = new[] { 34, 162, 16, 172, 181 };
						break;

					case 3:
						model.Lines = new[] { 53, 106, 135, 107 };
						break;

					case 4:
						model.Lines = new[] { 61, 95, 97, 118, 143, 188 };
						break;

					case 5:
						model.Lines = new[] { 12, 39, 41, 60, 61, 68, 95, 101, 106, 109, 111, 118, 132, 142, 152 };
						break;

					default:
						model.Lines = new int[0];
						break;
				}*/

				#endregion

				return new JsonActionResult(model);
			}
			catch (ValidationException ex)
			{
				return new JsonActionResult(new JsonResponse(ex));
			}
			catch (Exception ex)
			{
				return new JsonActionResult(new JsonResponse(false, Resources.Global.ErrorMessage));
			}
        }

		[HttpPost]
		public ActionResult Checkpoint(DataEntryModel data)
		{
			try
			{
				#region Validations

				if (string.IsNullOrEmpty(data.keyCode)) throw new ValidationException("El parámetro 'keyCode' es requerido.");
				
				if (string.IsNullOrEmpty(data.serialNumber)) throw new ValidationException("El parámetro 'serialNumber' es requerido.");
				
				if (!data.latitude.HasValue) throw new ValidationException("El parámetro 'latitude' es requerido.");

				if (!data.longitude.HasValue) throw new ValidationException("El parámetro 'longitude' es requerido");

				if (string.IsNullOrEmpty(data.datetime)) throw new ValidationException("El parámetro 'datetime' es requerido.");

				if (!IsValidDateTime(data.datetime)) throw new ValidationException("El parámetro 'datetime' es incorrecto.");
				
				if (!IsValidKeyCode(data)) throw new ValidationException("El keyCode es incorrecto.");
				
				#endregion Validations

				CheckpointComponent.Instance.Add(new DataEntryCheckpoint{
					SerialNumber = data.serialNumber,
					LineNumber = data.line,
					Coordinate = new GeoCoordinate(data.latitude.Value, data.longitude.Value),
					UserDateTime = ParseUserDateTime(data.datetime),
					DateTime = DateTimeHelper.Now()
				});
				
				return new JsonActionResult(new JsonResponse(true));
			}
			catch (ValidationException ex)
			{
				return new JsonActionResult(new JsonResponse(ex));
			}
			catch (Exception ex)
			{
				return new JsonActionResult(new JsonResponse(false, Resources.Global.ErrorMessage));
			}
		}
		
		#region Private Methods

		private static DateTime ParseUserDateTime(string datetime)
		{
			var year = Convert.ToInt32(datetime.Substring(0, 4));
			var month = Convert.ToInt32(datetime.Substring(4, 2));
			var day = Convert.ToInt32(datetime.Substring(6, 2));
			var hours = Convert.ToInt32(datetime.Substring(8, 2));
			var minutes = Convert.ToInt32(datetime.Substring(10, 2));
			var seconds = Convert.ToInt32(datetime.Substring(12, 2));

			return new DateTime(year, month, day, hours, minutes, seconds);
		}

		private static bool IsValidDateTime(string datetime)
		{
			if (string.IsNullOrEmpty(datetime)) return false;

			if (datetime.Length != 14) return false;
			
			try
			{
				ParseUserDateTime(datetime);

				return true;
			}
			catch (Exception)
			{
				return false;
			}
		}
		
		private static bool IsValidKeyCode(DataEntryModel data)
		{
			if (string.IsNullOrEmpty(data.keyCode)) return false;

			var seedString = string.Concat(data.serialNumber, "elgamugol", data.datetime);

			// use Password object to get MD5 hash of seedString
			// and compare to data.keyCode
			return new Password(seedString).Hash.Equals(data.keyCode, StringComparison.InvariantCultureIgnoreCase);
		}

    	#endregion Provate Methods
	}
}

server-website/Nostradabus.Website/Views/Checkpoint/Add.cshtml
@model Nostradabus.Website.Models.CheckpointModel
@using System.Globalization
@using Nostradabus.BusinessComponents		   
@{
    ViewBag.Title = "Add";
}

<h2>Add</h2>

@using (Html.BeginForm())
{
	<div>
		@Html.LabelFor(m => m.RouteId)
		@Html.DropDownListFor(m => m.RouteId, RouteComponent.Instance.GetAll().OrderBy(r => r.LineNumber).Select(r => new SelectListItem {Text = r.ToString(), Value = r.ID.ToString(CultureInfo.InvariantCulture), Selected = r.ID == Model.RouteId}), "")
		@Html.ValidationMessageFor(m => m.RouteId)
	</div>
	
	<div>
		@Html.LabelFor(m => m.UUID)
		@Html.EditorFor(m => m.UUID)
		@Html.ValidationMessageFor(m => m.UUID)
	</div>
	
	<div>
		@Html.LabelFor(m => m.Latitude)
		@Html.EditorFor(m => m.Latitude)
		@Html.ValidationMessageFor(m => m.Latitude)
	</div>
	
	<div>
		@Html.LabelFor(m => m.Longitude)
		@Html.EditorFor(m => m.Longitude)
		@Html.ValidationMessageFor(m => m.Longitude)
	</div>
	
	<div>
		@Html.LabelFor(m => m.DateTime)
		@Html.EditorFor(m => m.DateTime)
		@Html.ValidationMessageFor(m => m.DateTime)
	</div>
	
	<input type="submit" value="Registrar"/>
	
	<input type="button" value="Limpiar" onclick="$('select,input[type=text]').val('');"/>
}

server-website/Nostradabus.Website/Views/Checkpoint/DataEntry.cshtml
@model Nostradabus.Website.Models.DataEntryModel
@using System.Globalization
@using Nostradabus.BusinessComponents
@{
	ViewBag.Title = "Mobile Data Entry";
}

<h2>Mobile Data Entry Simulation</h2>

@using (Html.BeginForm("Checkpoint", "Mobile"))
{
	<div>
		@Html.LabelFor(m => m.serialNumber)
		@Html.EditorFor(m => m.serialNumber)
		@Html.ValidationMessageFor(m => m.serialNumber)
	</div>
	
	<div>
		@Html.LabelFor(m => m.line)
		@Html.EditorFor(m => m.line)
		@Html.ValidationMessageFor(m => m.line)
	</div>
	
	<div>
		@Html.LabelFor(m => m.latitude)
		@Html.EditorFor(m => m.latitude)
		@Html.ValidationMessageFor(m => m.latitude)
	</div>
	
	<div>
		@Html.LabelFor(m => m.longitude)
		@Html.EditorFor(m => m.longitude)
		@Html.ValidationMessageFor(m => m.longitude)
	</div>
	
	<div>
		@Html.LabelFor(m => m.datetime)
		@Html.EditorFor(m => m.datetime)
		@Html.ValidationMessageFor(m => m.datetime)
	</div>
	
	<div>
		@Html.LabelFor(m => m.keyCode)
		@Html.EditorFor(m => m.keyCode)
		@Html.ValidationMessageFor(m => m.keyCode)
	</div>
	
	<div>
		@Html.LabelFor(m => m.speed)
		@Html.EditorFor(m => m.speed)
		@Html.ValidationMessageFor(m => m.speed)
	</div>
	
	<div>
		@Html.LabelFor(m => m.batteryStatus)
		@Html.EditorFor(m => m.batteryStatus)
		@Html.ValidationMessageFor(m => m.batteryStatus)
	</div>
	
	<input type="submit" value="Registrar"/>
	
	<input type="button" value="Limpiar" onclick="$('select,input[type=text]').val('');"/>
}